import Head from "next/head";
import { useState } from "react";
import Card from "../components/Card";

const data = [
    {
        name: "Tanya Sinclair",
        role: "UX Engineer",
        img: "/images/image-tanya.jpg",
        text: `“ I’ve been interested in coding for a while but never taken
                    the jump, until now. I couldn’t recommend this course
                    enough. I’m now in the job of my dreams and so excited about
                    the future. ”`,
    },

    {
        name: "John Tarkpor",
        role: "Junior Front-end Developer",
        img: "/images/image-john.jpg",
        text: `“ If you want to lay the best foundation possible I’d recommend taking this course. The depth the instructors go into is incredible. I now feel so confident about starting up as a professional developer. ”`,
    },
];

export default function Home() {
    const [opt, setOpt] = useState(0);

    const onChange = () => {
        if (opt === 0) {
            setOpt(1);
        } else {
            setOpt(0);
        }
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Card
                    name={data[opt].name}
                    role={data[opt].role}
                    img={data[opt].img}
                    text={data[opt].text}
                    onChange={onChange}
                />
            </main>
        </>
    );
}
